version: "3.9"

services:
  catalog-service:
    build:
      context: .
      dockerfile: src/CatalogService/Dockerfile
    container_name: catalog-service
    ports:
      - "8081:8080"

  order-service:
    build:
      context: .
      dockerfile: src/OrderService/Dockerfile
    container_name: order-service
    ports:
      - "8082:8080"
    environment:
      - CATALOG_SERVICE_BASE_URL=http://catalog-service:8080
    depends_on:
      - catalog-service    